### ISSUE TITLE
求助：The name 'SMS_Council' does not exist in the current context

### ISSUE THREAD

**Issue by sugarzyl** [yang991178/SMS_Council#2] opened 2018-01-15 09:55 UTC
Compiler Error Message: CS0103: The name 'SMS_Council' does not exist in the current context

Source Error:

 

Line 14:     <script src="js/materialize.min.js"></script>
Line 15:     <% 
Line 16:         var package = SMS_Council.Classes.User.IsLogin ? "usermanage" : "login";
Line 17:         Response.Write(SMS_Council.Classes.Helper.LoadAngular(package));
Line 18:     %>

**Comment by Liby99** [comment] 2018-01-15 09:58
Please include the url of the file that triggers this error so that we can tackle the problem easier.

**Comment by sugarzyl** [comment] 2018-01-15 10:22
http://localhost/
是我部署有问题吗?

**Comment by Liby99** [comment] 2018-01-15 10:23
I mean the url of the file in the Github Repo though hahaha. Like… xxxxx.aspx.cs?

**Comment by sugarzyl** [comment] 2018-01-15 10:27
Default.aspx

**Comment by Liby99** [comment] 2018-01-15 10:36
So then, your issue description should include url [https://github.com/yang991178/SMS_Council/blob/master/Default.aspx](https://github.com/yang991178/SMS_Council/blob/master/Default.aspx), or even better, written in markdown, [Default.aspx](https://github.com/yang991178/SMS_Council/blob/master/Default.aspx), so that others who view this issue can click on the url and get to where they need.

For the problem, to me, it seems like you didn't use the namespace in `Default.aspx.cs`. Try refer to other files like [ConferenceDetail.aspx.cs](https://github.com/yang991178/SMS_Council/blob/master/ConferenceDetail.aspx.cs) and, look at that 

``` c#
namespace SMS_Council
{
    ...
}
```

Wrap these lines outside your Default class definition.

**Comment by Liby99** [comment] 2018-01-15 10:43
Just for reference: All the `.aspx` files will be ran under the context of its corresponding `.aspx.cs` file. 
By the way good job on submitting issues here. ∠( ᐛ 」∠)＿.

**Comment by yang991178** [comment] 2018-01-16 01:17
啊，因为我还没有把数据库架构发上来，所以目前应该是无法运行的。
以后的开发者：请检查Web.config是否按照[Web.example.config](https://github.com/yang991178/SMS_Council/blob/master/Web.example.config)和你的数据库有效配置，项目的引用有没有包含SMS_Council类。

还有，你们是不是同一个人啊？

**Comment by Liby99** [comment] 2018-01-16 01:21
What are you talking about... Same person? Who?
BTW @yang991178 I was Tech Department Chair in SAA back in 2014. I have met you already.
Also if the issue is resolved please close it.

**Comment by sugarzyl** [comment] 2018-01-16 02:45
@yang991178 最终版的和数据库可以给我发一下吗？394983724@qq.com，谢谢

**Closed as completed** 2018-02-07 12:47 UTC
